require("mini.git").setup({})
vim.keymap.set("n", "<leader>gb", ":vert Git blame -- %<CR>", { desc = "[Git] Blame" })
vim.keymap.set("n", "<leader>gl", ":Git log --oneline<CR>", { desc = "[Git] Log" })
vim.keymap.set("n", "<leader>gs", ":Git status<CR>", { desc = "[Git] Status" })
vim.keymap.set("n", "<leader>gd", ":Git diff<CR>", { desc = "[Git] Diff" })
vim.keymap.set("n", "<leader>gh", MiniGit.show_at_cursor, { desc = "[Git] History at cursor" })
